# Generated by Django 5.2.1 on 2026-03-23 21:07

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_recipe_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=blog.models.recipe_image_path),
        ),
    ]
